services:
  modbus-client:
    build:
      context: .  # Указываем путь к текущей папке, где находится Dockerfile.client
      dockerfile: Dockerfile.client  # Указываем имя Dockerfile для клиента
    depends_on:
      - dbpostgres  # Говорим, что клиент также зависит от PostgreSQL
    networks:
      - modbus-network
    stdin_open: true
    tty: true
    ports:
      - "8081:8080"  # Пробрасываем порт 8081 на хост и 8080 внутри контейнера

  dbpostgres:
    image: postgres:latest  # Используем официальный образ PostgreSQL
    environment:
      POSTGRES_USER: postgres  # Задаем пользователя базы данных
      POSTGRES_PASSWORD: postgres  # Задаем пароль
      POSTGRES_DB: postgres  # Имя базы данных
    ports:
      - "5439:5439"  # Пробрасываем порт 5439
    networks:
      - modbus-network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные вне контейнера

networks:
  modbus-network:
    driver: bridge  # Изменено на bridge

volumes:
  postgres_data:  # Создаем volume для данных PostgreSQL
